Algoritmo "faccat06"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : calcular a área de um retângulo! (area)
// Autor(a)    : Bernardo Prieto
// Data atual  : 01/10/2023
Var
altura, base, area: real


Inicio
escreval("Informe a base do retângulo!")
leia(base)
escreval("Informe a altura do retângulo!")
leia(altura)
area<-base*altura
escreval("A área do retângulo é de: ", area)


Fimalgoritmo