Algoritmo "faccat15"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Verificar se o número é positivo ou negativo!
// Autor(a)    : Bernardo Prieto
// Data atual  : 03/10/2023
Var
   numero: inteiro

Inicio
   escreval("Informe o número")
   leia(numero)
   se numero < 0 entao
      escreval("Numero negativo!")
   senao
      escreval("Numero positivo!")
   fimse




Fimalgoritmo