Algoritmo "Faccat05"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Ler o antecessor de um número! (antecessor)
// Autor(a)    : Bernardo Prieto
// Data atual  : 01/10/2023
Var
numero, antecessor: inteiro



Inicio
escreval("Informe um número!")
leia(numero)
antecessor<-numero-1
escreval("O antecessor de: ", numero," é ", antecessor)





Fimalgoritmo