Algoritmo "faccat10"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Calcular a porcentagem de um valor de um carro!
// (comissão)
// Autor(a)    : Bernardo Prieto
// Data atual  : 02/10/2023
Var
custoFabrica,impostos,valorTotal:real

Inicio
escreval("Informe o custo de fábrica!")
leia(custoFabrica)
valorTotal<-custoFabrica+((custoFabrica*28)/100)+((custoFabrica*45)/100)
escreval("O valor do veículo é de ",valorTotal,"R$")
Fimalgoritmo